#!/bin/sh
# This is a basic convenience script that allows running an arbitrary command inside
# The cross-compiling docker container

# determine if we need to use sudo when calling docker
if groups $USER | grep -q docker;
then
    DOCKER=docker
else
    DOCKER="sudo docker"
fi
$DOCKER run -it -u $(id -u):$(id -g) -v "$PWD":/ros_ws "reem17/rosberrypi-xcompile:iron" $@

