#!/bin/sh
. /opt/ros/humble/setup.sh
colcon build --build-base aarch64_build --install-base aarch64_install --cmake-args -DCMAKE_TOOLCHAIN_FILE=/toolchain.cmake -DCMAKE_INSTALL_PREFIX=aarch64_install $@
