#!/bin/sh
# Convenience wrapper around opencr_ld_shell_arm64 designed
# To always load the nuburger firmware on the turtlebot
opencr_ld_shell_arm64 /dev/ttyACM0 115200 /usr/local/bin/nuburger.opencr 1
